SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `Content`;

CREATE TABLE `Content` (
  `id` INT(10) NOT NULL AUTO_INCREMENT,
  `title` TEXT NOT NULL,
  `content` TEXT NOT NULL,
  `type` VARCHAR(10) NOT NULL DEFAULT "",
  `status` VARCHAR(10) NOT NULL DEFAULT "",
  `create_time` DATETIME NOT NULL DEFAULT TIMESTAMP,
  `modify_time` DATETIME NOT NULL DEFAULT TIMESTAMP,
  PRIMARY KEY(`id`)
) ENGINE=InnoDB DEFAULT CHARSET = utf8;

CREATE INDEX ContentIndex ON Content(type,status);